### Importing modules

In [1]:
import pandas as pd

### Loading STRUCTURE q matrices

In [8]:
q_2 = pd.read_csv('../data/structure/q_matrix_2', index_col=0)
q_2 = q_2.apply(pd.to_numeric)
q_2['max_prob'] = q_2.iloc[:, 1:].max(axis=1)
q_2['cluster_assignment'] = q_2.iloc[:, 1:-1].idxmax(axis=1)
q_2['Cluster'] = q_2['cluster_assignment'].apply(lambda x: x.split('_')[-1])
q_2

     prop_missing  prop_1  prop_2  max_prob cluster_assignment Cluster
0            0.01   0.827   0.173     0.827             prop_1       1
1            0.02   0.224   0.776     0.776             prop_2       2
2            0.03   0.356   0.644     0.644             prop_2       2
3            0.02   0.941   0.059     0.941             prop_1       1
4            0.00   0.326   0.674     0.674             prop_2       2
..            ...     ...     ...       ...                ...     ...
239          0.04   0.998   0.002     0.998             prop_1       1
240          0.03   0.996   0.004     0.996             prop_1       1
241          0.10   0.965   0.035     0.965             prop_1       1
242          0.00   0.941   0.059     0.941             prop_1       1
243          0.04   0.996   0.004     0.996             prop_1       1

[244 rows x 6 columns]

In [10]:
q_2.groupby('Cluster').count()

         prop_missing  prop_1  prop_2  max_prob  cluster_assignment
Cluster
1                  53      53      53        53                  53
2                 191     191     191       191                 191

In [13]:
q_3 = pd.read_csv('../data/structure/q_matrix_3', index_col=0)
q_3 = q_3.apply(pd.to_numeric)
q_3['max_prob'] = q_3.iloc[:, 1:].max(axis=1)
q_3['cluster_assignment'] = q_3.iloc[:, 1:-1].idxmax(axis=1)
q_3['Cluster'] = q_3['cluster_assignment'].apply(lambda x: x.split('_')[-1])
q_3

     prop_missing  prop_1  prop_2  prop_3  max_prob cluster_assignment Cluster
0            0.01   0.690   0.012   0.298     0.690             prop_1       1
1            0.02   0.042   0.009   0.949     0.949             prop_3       3
2            0.03   0.042   0.002   0.956     0.956             prop_3       3
3            0.02   0.668   0.002   0.330     0.668             prop_1       1
4            0.00   0.123   0.005   0.872     0.872             prop_3       3
..            ...     ...     ...     ...       ...                ...     ...
239          0.04   0.998   0.001   0.001     0.998             prop_1       1
240          0.03   0.997   0.002   0.002     0.997             prop_1       1
241          0.10   0.740   0.003   0.257     0.740             prop_1       1
242          0.00   0.898   0.083   0.018     0.898             prop_1       1
243          0.04   0.994   0.002   0.004     0.994             prop_1       1

[244 rows x 7 columns]

In [14]:
q_3.groupby('Cluster').count()

         prop_missing  prop_1  prop_2  prop_3  max_prob  cluster_assignment
Cluster
1                  48      48      48      48        48                  48
2                 114     114     114     114       114                 114
3                  82      82      82      82        82                  82

### Where do samples go from K = 2 to K = 3?

In [81]:
q_2.merge(q_3, left_index=True, right_index=True)[['Cluster_x','Cluster_y']]

    Cluster_x Cluster_y
0           1         1
1           2         3
2           2         3
3           1         1
4           2         3
..        ...       ...
239         1         1
240         1         1
241         1         1
242         1         1
243         1         1

[244 rows x 2 columns]

In [83]:
q_2.merge(q_3, left_index=True, right_index=True)[['Cluster_x','Cluster_y']].groupby(['Cluster_x','Cluster_y']).size()

Cluster_x  Cluster_y
1          1             48
           2              1
           3              4
2          2            113
           3             78
dtype: int64

In [6]:
pd.read_csv('../data/genotypes/fst_input_apriori', index_col=0).groupby('POP').size()

POP
AR          29
IA_NE       11
IL_IN       13
KS_OK       12
KY_TN       59
LA           6
MI           5
MN_WI_ND    26
MO          48
MS          15
OH_WV       11
SC_NC        9
dtype: int64