### Importing modules

In [2]:
import pandas as pd

In [3]:
allele_stats_2 = pd.read_table('../tables/allele_stats_2.tab')
allele_stats_2.index = ['NW','SW & E']
allele_stats_2.round(3)

,Allelic_Richness,Observed_Heterozygosity,Expected_Heterozygosity,N,Fis,Private_Alleles
NW,1.696,0.159,0.165,50.808,0.033,11
SW & E,1.874,0.173,0.183,180.036,0.053,446

In [5]:
allele_stats_3 = pd.read_table('../tables/allele_stats_3.tab')
allele_stats_3.index = ['NW','E','SW']
allele_stats_3.round(3)

,Allelic_Richness,Observed_Heterozygosity,Expected_Heterozygosity,N,Fis,Private_Alleles
NW,1.660,0.158,0.163,45.836,0.030,10
E,1.831,0.175,0.184,107.176,0.043,127
SW,1.776,0.170,0.177,77.831,0.036,38

In [11]:
allele_stats_ap = pd.read_table('../tables/allele_stats_apriori.tab')
allele_stats_ap.index = allele_stats_ap['Population']
allele_stats_ap.round(3)[['N','Allelic_Richness','Observed_Heterozygosity',
                         'Expected_Heterozygosity','Fis','Private_Alleles']]

,N,Allelic_Richness,Observed_Heterozygosity,Expected_Heterozygosity,Fis,Private_Alleles
Population,,,,,,
AR,26.941,1.175,0.168,0.175,0.031,0
IA_NE,10.647,1.166,0.161,0.166,0.025,0
IL_IN,12.422,1.177,0.172,0.177,0.017,0
KS_OK,11.496,1.180,0.173,0.180,0.034,0
KY_TN,55.323,1.184,0.176,0.184,0.038,7
LA,5.601,1.184,0.178,0.185,0.017,0
MI,4.547,1.174,0.173,NaN,-0.016,0
MN_WI_ND,24.950,1.157,0.154,0.157,0.017,1
MO,45.750,1.174,0.169,0.174,0.028,3
MS,14.507,1.181,0.178,0.181,0.016,1
OH_WV,10.294,1.173,0.168,0.174,0.024,1
SC_NC,8.366,1.173,0.177,0.172,-0.022,1